/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import speedplay.InfoFromServer;
import speedplay.Player;
import speedplay.Question;

/**
 *
 * @author Tichnut
 */
public class ViewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form ViewQuestion
     */
    private ClientSend clientSend;
    private Player player;
    private Question question;
    private Thread ReadObject;
    private DefaultListModel listModel = new DefaultListModel();
    private String winner;
//private boolean flag=false;

    public ViewQuestion() {
        initComponents();
        jAns1Bth.setVisible(false);
        jAns2Bth.setVisible(false);
        jAns3Bth_.setVisible(false);
        jAns4Bth_.setVisible(false);
        jWinnerLbl.setVisible(false);
        jquestuonTextPane.setVisible(false);
        player = new Player();
        ReadObject = new Thread(() -> {
            while (true) {
                InfoFromServer input = clientSend.ReadFromSever();
                GetObjectFromServer(input);
            }
        });
        try {
//192.168.0.133
            clientSend = new ClientSend(1700, "127.0.0.1");
            
        } catch (IOException ex) {
            Logger.getLogger(ViewQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void SendName(String name) {
        clientSend.SendToServer(name);
        JOptionPane.showMessageDialog(ViewQuestion.this, "הצטרפת בהצלחה למשחק", "שים לב", JOptionPane.INFORMATION_MESSAGE);
        jnamePlayerLbl.setText(name);
        ReadObject.start();
        //question = clientSend.getQuestion();

    }
    //מטפל בקלט שהתקבל מהשרת

    public void GetObjectFromServer(InfoFromServer infoFromServer) {
        jAns1Bth.setVisible(true);
        jAns2Bth.setVisible(true);
        jAns3Bth_.setVisible(true);
        jAns4Bth_.setVisible(true);
        jMessegelbl.setVisible(false);
        jWinnerLbl.setVisible(true);
        jquestuonTextPane.setVisible(true);
        switch (infoFromServer.getTypeInfo()) {
            case question:
                setQuestion(infoFromServer.getInfo());
                break;
//            case players:
//                setPlayers(infoFromServer.getInfo());
            case winner:
                setWinner(infoFromServer.getInfo());
                break;
            case endPlay:
                FinishPlayFram fram = new FinishPlayFram();
                fram.setWinner(winner, jnamePlayerLbl.getText());
                fram.setVisible(true);
                this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPlayersList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPlayersPanel = new javax.swing.JPanel();
        jqustionlbl = new javax.swing.JLabel();
        jAns2Bth = new javax.swing.JButton();
        jAns1Bth = new javax.swing.JButton();
        jMessegelbl = new javax.swing.JLabel();
        jAns3Bth_ = new javax.swing.JButton();
        jAns4Bth_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jquestuonTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpointsLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnamePlayerLbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jWinnerLbl = new javax.swing.JTextPane();

        jPlayersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jPlayersList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N

        jPlayersPanel.setBackground(new java.awt.Color(255, 255, 255));

        jqustionlbl.setText("             ");

        jAns2Bth.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jAns2Bth.setText("jButton1");
        jAns2Bth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAns2BthActionPerformed(evt);
            }
        });

        jAns1Bth.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jAns1Bth.setText("jButton1");
        jAns1Bth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAns1BthActionPerformed(evt);
            }
        });

        jMessegelbl.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jMessegelbl.setText("היה מוכן . כאשר כל השחקנים יכנסו המשחק יתחיל.");

        jAns3Bth_.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jAns3Bth_.setText("jButton1");
        jAns3Bth_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAns3Bth_ActionPerformed(evt);
            }
        });

        jAns4Bth_.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jAns4Bth_.setText("1000");
        jAns4Bth_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAns4Bth_ActionPerformed(evt);
            }
        });

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jquestuonTextPane.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jScrollPane2.setViewportView(jquestuonTextPane);

        javax.swing.GroupLayout jPlayersPanelLayout = new javax.swing.GroupLayout(jPlayersPanel);
        jPlayersPanel.setLayout(jPlayersPanelLayout);
        jPlayersPanelLayout.setHorizontalGroup(
            jPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPlayersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAns4Bth_, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jAns3Bth_, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jAns2Bth, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jAns1Bth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPlayersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPlayersPanelLayout.createSequentialGroup()
                        .addComponent(jqustionlbl)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPlayersPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(jPlayersPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jMessegelbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPlayersPanelLayout.setVerticalGroup(
            jPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPlayersPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jqustionlbl)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMessegelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPlayersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAns2Bth, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAns1Bth, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAns3Bth_, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAns4Bth_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("מספר הנקודות שלך");

        jLabel2.setText("0");

        jpointsLbl.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        jpointsLbl.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("השחקן האלוף ביותר");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("בהצלחה במשחק ");

        jnamePlayerLbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jnamePlayerLbl.setText("            ");

        jWinnerLbl.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jScrollPane4.setViewportView(jWinnerLbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jnamePlayerLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(238, 238, 238))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPlayersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jpointsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jnamePlayerLbl))
                .addGap(18, 18, 18)
                .addComponent(jPlayersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpointsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAns1BthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAns1BthActionPerformed
        //שולח לשרת שעניתי תשובה
        clientSend.SendToServer(0);
        CheckAns(0);
    }//GEN-LAST:event_jAns1BthActionPerformed

    private void jAns2BthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAns2BthActionPerformed
        //שולח לשרת שעניתי תשובה
        clientSend.SendToServer(1);
        CheckAns(1);
    }//GEN-LAST:event_jAns2BthActionPerformed

    private void jAns3Bth_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAns3Bth_ActionPerformed
        clientSend.SendToServer(2);
        System.out.println("perfect");
        CheckAns(2);
        
    }//GEN-LAST:event_jAns3Bth_ActionPerformed

    private void jAns4Bth_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAns4Bth_ActionPerformed
        // TODO add your handling code here:
        clientSend.SendToServer(2);
        CheckAns(3);
        System.out.println("perfect");
    }//GEN-LAST:event_jAns4Bth_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAns1Bth;
    private javax.swing.JButton jAns2Bth;
    private javax.swing.JButton jAns3Bth_;
    private javax.swing.JButton jAns4Bth_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMessegelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> jPlayersList;
    private javax.swing.JPanel jPlayersPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jWinnerLbl;
    private javax.swing.JLabel jnamePlayerLbl;
    private javax.swing.JLabel jpointsLbl;
    private javax.swing.JTextPane jquestuonTextPane;
    private javax.swing.JLabel jqustionlbl;
    // End of variables declaration//GEN-END:variables

    private void setQuestion(Object info) {
        this.question = (Question) info;
        Fillquestion();
    }

//    private void setPlayers(Object info) {
//        ArrayList<Player> players = (ArrayList<Player>) info;
//        listModel.clear();
//        for (Player player : players) {
//            listModel.addElement(player);
//        }
//        jPlayersList.setModel(listModel);
//    }
    private void setWinner(Object info) {
        winner = (String) info;
        jWinnerLbl.setText(winner);
    }
    
    private void CheckAns(int ansId) {
        
        int x = question.getNumRight();
        if (ansId == question.getNumRight()) {
            JOptionPane.showMessageDialog(ViewQuestion.this, "תשובה נכונה" + "נוספו לך חמש נקודות", "שים לב", JOptionPane.INFORMATION_MESSAGE);
            player.addPoint(5);
        } else {
            JOptionPane.showMessageDialog(ViewQuestion.this, "תשובה שגויה, ירדו לך עשר נקודות", "שים לב", JOptionPane.INFORMATION_MESSAGE);
            player.subPoint(10);
        }
        jpointsLbl.setText(String.valueOf(player.getPoints()));
        jWinnerLbl.setVisible(true);
    }
    
    private void Fillquestion() {
        //jqustionlbl.setText(question.getQuestion());
        jquestuonTextPane.setText(question.getQuestion());
        jAns1Bth.setText(question.getAnswers().get(0));
        jAns2Bth.setText(question.getAnswers().get(1));
        jAns3Bth_.setText(question.getAnswers().get(2));
        jAns4Bth_.setText(question.getAnswers().get(3));
        
    }
}
